"""Initial migration - Create all database tables.

This migration creates the complete initial schema for the Superadmin Server,
including tables for tenant admins, tenants, pricing configurations, and
recharge orders.

Revision ID: 001
Revises: 
Create Date: 2026-09-20 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema to current version."""
    
    # ### commands auto generated by Alembic - 001_initial_schema ###
    
    # Create tenant_admins table
    op.create_table('tenant_admins',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=False, default=False),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_tenant_admins'),
        sa.UniqueConstraint('username', name='uq_tenant_admins_username'),
        sa.UniqueConstraint('email', name='uq_tenant_admins_email')
    )
    op.create_index('ix_tenant_admins_email', 'tenant_admins', ['email'], unique=False)
    op.create_index('ix_tenant_admins_username', 'tenant_admins', ['username'], unique=False)
    
    # Create tenants table
    op.create_table('tenants',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=True),
        sa.Column('contact_email', sa.String(length=255), nullable=True),
        sa.Column('contact_phone', sa.String(length=50), nullable=True),
        sa.Column('address', sa.String(length=500), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('balance_fen', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('total_recharge_fen', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('settings', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_tenants'),
        sa.UniqueConstraint('tenant_id', name='uq_tenants_tenant_id')
    )
    op.create_index('ix_tenants_contact_email', 'tenants', ['contact_email'], unique=False)
    op.create_index('ix_tenants_tenant_id', 'tenants', ['tenant_id'], unique=False)
    
    # Create pricing_configurations table
    op.create_table('pricing_configurations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('subject', sa.String(length=50), nullable=False),
        sa.Column('base_price_fen', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('currency', sa.String(length=10), nullable=False, server_default='CNY'),
        sa.Column('exchange_rate', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('discount_percent', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('min_usage_fen', sa.BigInteger(), nullable=True),
        sa.Column('max_usage_fen', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
        sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_pricing_configurations'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name='fk_pricing_configurations_tenant_id_tenants'),
        sa.CheckConstraint('discount_percent BETWEEN 1 AND 100', name='ck_pricing_configurations_discount_range'),
        sa.CheckConstraint('exchange_rate >= 1', name='ck_pricing_configurations_exchange_rate_positive'),
        sa.CheckConstraint('priority >= 0', name='ck_pricing_configurations_priority_non_negative')
    )
    op.create_index('ix_pricing_configurations_tenant_id', 'pricing_configurations', ['tenant_id'], unique=False)
    op.create_index('ix_pricing_configurations_subject', 'pricing_configurations', ['subject'], unique=False)
    op.create_index('ix_pricing_configurations_is_active', 'pricing_configurations', ['is_active'], unique=False)
    
    # Create recharge_orders table
    op.create_table('recharge_orders',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('order_no', sa.String(length=50), nullable=False),
        sa.Column('tenant_id', sa.String(length=50), nullable=False),
        sa.Column('amount_fen', sa.BigInteger(), nullable=False),
        sa.Column('amount_yuan', sa.Float(precision=10, scale=2), nullable=False),
        sa.Column('actual_payment_cents', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('points_ratio', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('bonus_points_fen', sa.BigInteger(), nullable=True, server_default='0'),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('payment_method', sa.String(length=50), nullable=True),
        sa.Column('payment_reference', sa.String(length=100), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_recharge_orders'),
        sa.UniqueConstraint('order_no', name='uq_recharge_orders_order_no'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name='fk_recharge_orders_tenant_id_tenants'),
        sa.CheckConstraint('amount_fen > 0', name='ck_recharge_orders_amount_positive'),
        sa.CheckConstraint('amount_yuan > 0', name='ck_recharge_orders_amount_yuan_positive'),
        sa.CheckConstraint('actual_payment_cents >= 0', name='ck_recharge_orders_payment_non_negative'),
        sa.CheckConstraint('points_ratio >= 1', name='ck_recharge_orders_ratio_positive'),
        sa.CheckConstraint('bonus_points_fen >= 0', name='ck_recharge_orders_bonus_non_negative')
    )
    op.create_index('ix_recharge_orders_order_no', 'recharge_orders', ['order_no'], unique=False)
    op.create_index('ix_recharge_orders_tenant_id', 'recharge_orders', ['tenant_id'], unique=False)
    op.create_index('ix_recharge_orders_status', 'recharge_orders', ['status'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema to previous version."""
    
    # ### commands auto generated by Alembic - 001_initial_schema ###
    
    op.drop_index('ix_recharge_orders_status', table_name='recharge_orders')
    op.drop_index('ix_recharge_orders_tenant_id', table_name='recharge_orders')
    op.drop_index('ix_recharge_orders_order_no', table_name='recharge_orders')
    op.drop_table('recharge_orders')
    
    op.drop_index('ix_pricing_configurations_is_active', table_name='pricing_configurations')
    op.drop_index('ix_pricing_configurations_subject', table_name='pricing_configurations')
    op.drop_index('ix_pricing_configurations_tenant_id', table_name='pricing_configurations')
    op.drop_table('pricing_configurations')
    
    op.drop_index('ix_tenants_tenant_id', table_name='tenants')
    op.drop_index('ix_tenants_contact_email', table_name='tenants')
    op.drop_table('tenants')
    
    op.drop_index('ix_tenant_admins_username', table_name='tenant_admins')
    op.drop_index('ix_tenant_admins_email', table_name='tenant_admins')
    op.drop_table('tenant_admins')
    
    # ### end Alembic commands ###
