# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d-%%(month).2d-%%(day).2d_%%(hour).2d-%%(minute).2d-%%(second).2d_%%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file environment if supported by pytz
# timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version path specification
# version_path_separator = NS

# set to 'true' to search source files recursively
# in each "the_dir" directory specified below
# recursive_version_path_search = false

# time interval between auto-generating migrations
# autogenerate_interval = 600 seconds

# version paths specification
# version_paths = /path/to/version/dir

# source code directory for migration scripts
# include_pattern = *.py

# template used to generate branch names
# branch_name_template = %(batch_name)s

# sqlalchemy.url = postgresql+asyncpg://user:password@localhost/superadmin_dev

[post_write_hooks]
# hooks = black
# Isort is disabled via command line argument during post_write_hook execution
# black.format_sql_file = True
# black.path = black
# black.invocation_line = invoker

# Use this option to customize how log messages are formatted
# logging.config_file = logger.conf

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
