// 中文审计词典，与服务端审计业务映射保持一致；未知历史事件明确待核对。
import type { AuditLogItem } from "../api.admin";
export const AUDIT_EVENT_LABELS: Record<string, string> = {
  ADMIN_ADJUSTMENT: "人工调整积分",
  ADMIN_DEVICE_UNBIND: "解绑设备",
  ADMIN_DEVICE_DISABLE: "永久禁用设备",
  ADMIN_DEVICE_REVOKE: "永久禁用设备",
  ADMIN_DEVICE_PAIRING_ADMIN_APPROVED: "管理员批准设备绑定",
  ADMIN_DEVICE_REPLACE: "替换绑定设备",
  ADMIN_SESSION_LOGOUT: "下线",
  ADMIN_SESSION_SWITCH: "切换登录设备",
  "analysis.create": "创建视频拆解",
  ACTIVATION_CODE_ISSUED: "启用激活码",
  ACTIVATION_CODE_ACTIVATED: "激活客户账户",
  ACTIVATION_CODE_SUSPENDED: "暂停激活码",
  ACTIVATION_CODE_RESUMED: "恢复激活码",
  ACTIVATION_CODE_REVOKED: "撤销激活码",
  ACTIVATION_CODE_ARCHIVED: "归档激活码",
  ACTIVATION_CODE_DELIVERED: "交付激活码",
  "admin.activation_code.archived": "归档激活码",
  "admin.activation_code.revealed": "查看激活码明文",
  "admin.activation_code.revealed_replay": "查看激活码明文（重放）",
  "admin.activation_code_batch.created": "创建激活码批次",
  "customer.suspend": "暂停客户",
  "customer.resume": "恢复客户",
  "customer_annotation.update": "修改客户标注",
  "customer.annotations.update": "修改客户标注",
  "customer_unit_price.update": "修改客户单价",
  "customer_unit_price.reset": "恢复客户默认单价",
  "customer_adjustment.create": "提交人工调整",
  "customer_package.grant": "开通套餐（已收款）",
  "customer_discount.create": "设置专项折扣",
  "customer_discount.deactivate": "停用专项折扣",
  "customer_pricing.update": "修改全局报价",
  "operation_rate.update": "修改业务价格",
  "billing.tariff.update": "修改业务售价与成本",
  "billing_settings.update": "修改充值与计价设置",
  "recharge_package.create": "新增充值套餐",
  "recharge_package.update": "修改充值套餐",
  "registration_bonus.settings.update": "修改注册赠送",
  "payment.sync": "同步收款状态",
  "payment.ledger_repair": "补记已收款积分",
  "payment.provider.update": "修改支付方式",
  "payment.wechat.update": "修改微信收款配置",
  "zpay_settings.update": "修改收款通道配置",
  "provider_settings.update": "修改服务配置",
  "provider_settings.secret_reveal": "查看接口密钥明文",
  "provider_settings.paid_test": "付费连接测试",
  "runtime_settings.update": "修改运行参数",
  "h3.account.update": "修改视频服务账号",
  "viral_runtime.update": "修改采集设置",
  "viral_platform.probe": "探测采集平台连接",
  "control.export": "导出数据",
  "control.reconciliation.read": "查看对账结果",
  "external_call.response_view": "查看接口原始响应",
  "generation_record.content_view": "查看生成内容",
  "generation_record.thumbnail_view": "查看生成缩略图",
  "admin_session.password_login": "管理员密码登录",
  "admin_session.exchange": "使用恢复凭据登录",
  "admin_team.create": "新增团队成员",
  "admin_team.update": "修改团队权限",
  "admin_team.password_reset": "重置团队成员密码",
  "team.member.create": "新增团队成员",
  "team.member.update": "修改团队权限",
  "team.member.password_reset": "重置团队成员密码",
};
export const AUDIT_GROUP_MEMBERS: Record<string, ReadonlySet<string>> = {
  content: new Set(["viral_runtime.update", "viral_platform.probe"]),
  funds: new Set([
    "ADMIN_ADJUSTMENT",
    "payment.sync",
    "payment.ledger_repair",
    "customer_adjustment.create",
    "customer_package.grant",
  ]),
  pricing: new Set([
    "operation_rate.update",
    "billing.tariff.update",
    "customer_pricing.update",
    "customer_unit_price.update",
    "customer_unit_price.reset",
    "recharge_package.create",
    "recharge_package.update",
    "customer_discount.create",
    "customer_discount.deactivate",
    "customer_package.grant",
    "registration_bonus.settings.update",
  ]),
  account: new Set([
    "customer.suspend",
    "customer.resume",
    "customer_annotation.update",
    "customer.annotations.update",
    "admin.activation_code.archived",
    "ACTIVATION_CODE_SUSPENDED",
    "ACTIVATION_CODE_RESUMED",
    "ACTIVATION_CODE_REVOKED",
    "ACTIVATION_CODE_ACTIVATED",
    "ADMIN_DEVICE_PAIRING_ADMIN_APPROVED",
    "ADMIN_DEVICE_REPLACE",
    "ADMIN_DEVICE_DISABLE",
    "ADMIN_DEVICE_UNBIND",
    "ADMIN_SESSION_LOGOUT",
    "h3.account.update",
    "admin.activation_code_batch.created",
    "ACTIVATION_CODE_ISSUED",
    "ACTIVATION_CODE_ARCHIVED",
    "ACTIVATION_CODE_DELIVERED",
  ]),
  system: new Set([
    "provider_settings.update",
    "provider_settings.paid_test",
    "billing_settings.update",
    "zpay_settings.update",
    "admin_team.create",
    "admin_team.update",
    "admin_team.password_reset",
    "team.member.create",
    "team.member.update",
    "team.member.password_reset",
    "runtime_settings.update",
    "payment.provider.update",
    "payment.wechat.update",
    "control.reconciliation.read",
  ]),
  secret_export: new Set([
    "provider_settings.secret_reveal",
    "admin.activation_code.revealed",
    "admin.activation_code.revealed_replay",
    "external_call.response_view",
    "control.export",
  ]),
  login: new Set(["admin_session.password_login", "admin_session.exchange"]),
};
export const BILLING_SERVICE_NAMES: Record<string, string> = {
  video_768p: "视频生成 · 768P",
  video_2k: "视频生成 · 2K",
  analysis: "视频分析",
  first_frame: "首帧图片",
  character: "人物形象及任务图片",
  rewrite: "文案改写",
  oral: "数字人口播",
  asr: "语音转写",
  viral_data: "爆款视频数据请求",
  viral_search: "爆款视频搜索",
  viral_search_refresh: "爆款视频刷新",
  viral_statistics: "爆款视频互动统计",
  viral_detail: "爆款视频详情",
  viral_copy: "爆款视频文案",
  link_resolution: "链接解析",
  prompt_optimize: "提示词 AI 优化",
  avatar_clone: "口播分身创建",
  voice_clone: "声音克隆",
  quality_inspection: "图片及视频质量检查",
  analysis_repair: "分析结果修复",
  analysis_repair_deepseek: "分析结果修复 · DeepSeek",
  cos: "云存储",
  zpay: "支付通道",
};
export function auditEventLabel(item: AuditLogItem): string {
  return (
    item.event_label ??
    AUDIT_EVENT_LABELS[item.event_type] ??
    "未映射操作（待核对）"
  );
}
export function auditGroupLabel(item: AuditLogItem): string {
  if (item.event_group_label) return item.event_group_label;
  const labels: Record<string, string> = {
    funds: "资金",
    pricing: "价格与套餐",
    account: "账号与设备",
    system: "系统配置",
    content: "内容与采集",
    secret_export: "密钥与导出",
    login: "登录",
  };
  const group = Object.entries(AUDIT_GROUP_MEMBERS).find(([, events]) =>
    events.has(item.event_type),
  )?.[0];
  return group ? labels[group] : "待核对";
}
